# Generated by Django 6.0.3 on 2026-06-03 11:52

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome de quem vai usar a chave', max_length=100)),
                ('key', models.CharField(default=API.models.generate_api_key, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('resumo', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('categoria', models.CharField(choices=[('tecnologia', 'Tecnologia'), ('ciencia', 'Ciência'), ('educacao', 'Educação'), ('industria', 'Indústria'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('fonte', models.CharField(blank=True, max_length=100)),
                ('data_publicacao', models.DateField()),
                ('destaque', models.BooleanField(default=False)),
                ('visualizacoes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
