# Generated by Django 6.0.3 on 2026-03-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=20)),
                ('grau', models.CharField(max_length=50)),
                ('duracao_anos', models.IntegerField()),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='licenciatura/')),
                ('url_deisi', models.URLField(blank=True)),
                ('url_lusofona', models.URLField(blank=True)),
            ],
        ),
    ]
