# Generated by Django 6.0.3 on 2026-03-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_unidadecurricular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('url_perfil_lusofona', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='docentes/')),
            ],
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='docentes',
            field=models.ManyToManyField(blank=True, to='portfolio.docente'),
        ),
    ]
