# Generated by Django 6.0.3 on 2026-03-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_docente_unidadecurricular_docentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('conceitos_aplicados', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('url_video_demo', models.URLField(blank=True)),
                ('url_github', models.URLField(blank=True)),
                ('ano_realizacao', models.IntegerField()),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.unidadecurricular')),
            ],
        ),
    ]
