# Generated by Django 6.0.3 on 2026-04-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tecnologias/')),
                ('url_website', models.URLField(blank=True)),
                ('nivel_interesse', models.IntegerField(default=1)),
                ('categoria', models.CharField(choices=[('linguagem', 'Linguagem de Programação'), ('framework', 'Framework'), ('base_dados', 'Base de Dados'), ('ferramenta', 'Ferramenta'), ('outro', 'Outro')], default='outro', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, to='portfolio.tecnologia'),
        ),
    ]
