# Generated by Django 6.0.3 on 2026-04-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_tecnologia_projeto_tecnologias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnologia',
            name='tipo',
        ),
    ]
