# Generated by Django 6.0.3 on 2026-04-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_tecnologia_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('autores', models.CharField(max_length=200)),
                ('orientadores', models.CharField(blank=True, max_length=200, null=True)),
                ('curso', models.CharField(blank=True, max_length=200, null=True)),
                ('ano', models.IntegerField()),
                ('sumario', models.TextField(blank=True)),
                ('palavras_chave', models.CharField(blank=True, max_length=500)),
                ('areas', models.CharField(blank=True, max_length=500)),
                ('tecnologias', models.CharField(blank=True, max_length=500)),
                ('link_pdf', models.URLField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='tfcs/')),
                ('rating', models.IntegerField(default=1)),
            ],
        ),
    ]
