# Generated by Django 6.0.3 on 2026-04-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_tfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('tecnica', 'Técnica'), ('soft', 'Soft Skill'), ('linguagem', 'Linguagem')], default='tecnica', max_length=20)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermédio'), ('avancado', 'Avançado')], default='basico', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('projetos', models.ManyToManyField(blank=True, to='portfolio.projeto')),
                ('tecnologias', models.ManyToManyField(blank=True, to='portfolio.tecnologia')),
            ],
        ),
    ]
