# Generated by Django 6.0.3 on 2026-04-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_competencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('academica', 'Académica'), ('curso', 'Curso Online'), ('certificacao', 'Certificação'), ('workshop', 'Workshop'), ('outro', 'Outro')], default='curso', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('certificado_url', models.URLField(blank=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
    ]
