# Generated by Django 6.0.3 on 2026-04-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_formacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade_relacionada', models.CharField(max_length=100)),
                ('descricao_decisao', models.TextField(blank=True)),
                ('erros_correcoes', models.TextField(blank=True)),
                ('justificacao_modelacao', models.TextField(blank=True)),
                ('foto_papel', models.ImageField(blank=True, null=True, upload_to='making_of/')),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Making Of',
                'verbose_name_plural': 'Making Of',
                'ordering': ['-data_registo'],
            },
        ),
    ]
