# Generated by Django 6.0.3 on 2026-04-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_makingof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('hackathon', 'Hackathon'), ('conferencia', 'Conferência'), ('workshop', 'Workshop'), ('competicao', 'Competição'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('local', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('resultado', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('competencias', models.ManyToManyField(blank=True, to='portfolio.competencia')),
                ('tecnologias', models.ManyToManyField(blank=True, to='portfolio.tecnologia')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
