# Generated by Django 6.0.3 on 2026-04-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
