# Generated by Django 6.0.3 on 2026-06-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_delete_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('resumo', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('categoria', models.CharField(choices=[('tecnologia', 'Tecnologia'), ('ciencia', 'Ciência'), ('educacao', 'Educação'), ('industria', 'Indústria'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('fonte', models.CharField(blank=True, max_length=100)),
                ('data_publicacao', models.DateField()),
                ('destaque', models.BooleanField(default=False)),
                ('visualizacoes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
